AppSettings:
  SiteTitle: Beans n Memes
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
mysql:
  client:
    server: localhost
    sslmode: none
redis:
  client:
    host: localhost